name: "CD - Production"

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  publish-images-job:
    if: github.event.pull_request.merged == true
    name: Publish Docker Images
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    with:
      workflow_file_path: "ghcr.io/snippetservices-group4/auth-middleware:latest"
    secrets: inherit

  deploy-vm-job:
    needs: publish-images-job
    name: Deploy Images in VM
    uses: SnippetServices-Group4/Workflows/.github/workflows/deploy-images-vm.yaml@main
    with:
      environment: "production"
      service_name: "auth-middleware"
    secrets: inherit
